### ISSUE TITLE
Problem running demo

### ISSUE THREAD

**Issue by mixersoft** [Urigo/IonicCLI-Meteor-WhatsApp#3]
I did the following, and I'm getting an exception:

```
git clone https://github.com/DAB0mB/ionic-meteor-whatsapp.git 
cd ionic-meteor-whatsapp
bower install
npm install
ionic platform add ios
gulp
```

npm WARNings

```
npm WARN package.json whatsapp@1.1.1 No repository field.
npm WARN package.json whatsapp@1.1.1 No README data
npm WARN package.json whatsapp@1.1.1 No license field.
npm WARN unmet dependency /dev.snaphappi.com/_play/ionic-meteor-whatsapp/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/rimraf/node_modules/glob requires minimatch@'2 || 3' but will load
npm WARN unmet dependency /dev.snaphappi.com/_play/ionic-meteor-whatsapp/node_modules/gulp-sass/node_modules/node-sass/node_modules/node-gyp/node_modules/minimatch,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /dev.snaphappi.com/_play/ionic-meteor-whatsapp/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/chalk requires supports-color@'^2.0.0' but will load
npm WARN unmet dependency /dev.snaphappi.com/_play/ionic-meteor-whatsapp/node_modules/webpack/node_modules/supports-color,
npm WARN unmet dependency which is version 3.1.2
```

exception from `gulp`, `webpack` does not complete build.

```
Error: Cannot find module 'q'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/dev.snaphappi.com/_play/ionic-meteor-whatsapp/node_modules/bower/lib/commands/index.js:1:71)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by DAB0mB** [comment]
If you run the following command

```
npm install q
```

Does it still fail?

**Comment by DAB0mB** [comment]
Ok, I'm closing this issue due to unresponsiveness
